[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install",
  "cd server && npm install",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "npm run build:server",
  "npm run build:client"
]

[start]
cmd = "cd server && npm start"

