[phases.setup]
nixPkgs = ["nodejs_22", "curl", "wget"]

[phases.install]
cmds = [
  "npm install"
]

[phases.build]
cmds = [
  "npm run build:server",
  "cd client && npm run build"
]

[start]
cmd = "cd server && node dist/index.js"
